# Generated by Django 3.1.1 on 2020-09-19 18:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=150)),
                ('maker', models.CharField(max_length=150)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('dateAdded', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'articles',
                'db_table': 'articles_stock',
            },
        ),
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('dateAdded', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'db_table': 'article_categories',
            },
        ),
        migrations.CreateModel(
            name='ArticleKind',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'article_kinds',
                'db_table': 'article_kinds',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'users',
                'db_table': 'app_users',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('startTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('endTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='inventory.user')),
            ],
            options={
                'verbose_name_plural': 'sessions',
                'db_table': 'users_sessions',
            },
        ),
        migrations.CreateModel(
            name='StoreArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('shelf', models.CharField(max_length=155)),
                ('article', models.OneToOneField(db_column='article_id', on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.article')),
            ],
            options={
                'verbose_name_plural': 'store_articles',
                'db_table': 'articles_store',
            },
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('articleCount', models.IntegerField(default=0)),
                ('isAvail', models.BooleanField()),
                ('dateCreated', models.DateTimeField(db_column='date_created', default=django.utils.timezone.now)),
                ('article', models.ForeignKey(db_column='article_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.article')),
                ('session', models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, to='inventory.usersession')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='inventory.user')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(db_column='category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.articlecategory'),
        ),
        migrations.AddField(
            model_name='article',
            name='kind',
            field=models.ForeignKey(db_column='article_kind_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.articlekind'),
        ),
    ]
