# Generated by Django 3.1.1 on 2020-09-21 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0002_auto_20200920_0746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'verbose_name_plural': 'baskets'},
        ),
        migrations.AddField(
            model_name='user',
            name='auth',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='basket',
            table='goody_basket',
        ),
    ]
